[dependencies]
eventric-stream.workspace = true

[lints]
workspace = true

[package]
authors.workspace    = true
categories.workspace = true
description          = "Eventric Stream Profiling Examples"
edition.workspace    = true
keywords.workspace   = true
license.workspace    = true
name                 = "eventric-stream-profiling-examples"
readme.workspace     = true
repository.workspace = true
version.workspace    = true
