name: Audit

on:
  push:
    paths:
      - '**/Cargo.lock'
      - '**/audit.toml'
      - '**/deny.toml'
  pull_request:
    paths: 
      - '**/Cargo.lock'
      - '**/audit.toml'
      - '**/deny.toml'

jobs:
  call_shared:
    uses: eventrica/.github/.github/workflows/audit.yml@main
    secrets: inherit