name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry/index/
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache Build
      uses: actions/cache@v3
      with:
        path: target/
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}


    - name: Check Format
      run: cargo fmt --check

    - name: Check Lint
      run: cargo clippy --workspace --all-targets -- -D warnings

    - name: Build
      run: cargo build --workspace --verbose

    - name: Test
      run: cargo test --workspace --tests --verbose

    - name: Test Docs
      run: cargo test --workspace --doc --verbose

    - name: Test Examples
      run: cargo test --workspace --examples --verbose

    - name: Coverage
      run: |
        cargo install --locked cargo-tarpaulin
        cargo tarpaulin --workspace --out Xml --output-dir coverage

    - name: Coverage Upload
      uses: coverallsapp/github-action@v2
